# Generated by Django 2.1 on 2018-11-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GAState',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Process', models.FloatField(default=100)),
                ('Temperature', models.FloatField(default=0)),
                ('Path', models.CharField(max_length=10000)),
            ],
        ),
    ]
