# Generated by Django 2.1 on 2019-01-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA', '0002_auto_20190113_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastate',
            name='All',
            field=models.CharField(default='$', max_length=30000),
        ),
    ]
