# Generated by Django 2.1 on 2019-01-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA', '0003_gastate_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastate',
            name='All',
            field=models.CharField(max_length=30000),
        ),
    ]
