# Generated by Django 2.1.3 on 2018-11-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
            ],
        ),
    ]
