# Generated by Django 2.1.3 on 2018-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Process', models.FloatField(default=100)),
                ('Path', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SAState',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Process', models.FloatField(default=100)),
                ('Temperature', models.FloatField(default=0)),
                ('Path', models.CharField(max_length=10000)),
            ],
        ),
    ]
